name: pre-commit
on:
  pull_request:
  push:
    branches: [main]

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: |
        curl https://sh.rustup.rs -sSfy | sh
        source $HOME/.cargo/env
    - uses: pre-commit/action@v2.0.3
